nome = str(input("Digite seu nome completo: "))
idade = str(input("Digite sua idade: "))
ano_nascimento = str(input("digite seu ano de nascimento: "))
estado_civil = str(input("Qual seu estado civil? : "))
cidade_em_que_vive = str(input("cidade em que vive? : "))
print("Suas informações pessoais são: ")
print(nome)
print(idade)
print(ano_nascimento)
print(estado_civil)
print(cidade_em_que_vive)